# Generated by Django 3.2.12 on 2022-04-27 10:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('timee', '0004_auto_20220427_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='timee',
            name='date_in',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timee',
            name='date_out',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='timee',
            name='time_in',
            field=models.TimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='timee',
            name='time_out',
            field=models.TimeField(auto_now=True),
        ),
    ]
